@startuml
Class AAUOC{
newLocation(I:Location) : void
newEvent(e:Event) : void
newPerson(p:Person) : void
informEvent(e:Event) : void
register(m:Member, e:Event) : void
}
Class Person{
name : String
}
Class Location{
description : String
address : String
}
Class Event{
date: Date
description : String
assign(l : Location) : void
}
Class Member{
e-mail : String
}
Class Conference{
max_attendees : Integer
}

Event <|-- Conference
Event <|-- BoardMeeting

Event"0..*"  -- "0..*" Location : isLocatedIn
Event"0..*"  -- "0..*" Member : attendsTo

Person <|-- Member
Member <|-- BoardMember

AAUOC o-- "0..*" Event
AAUOC o-- "0..*" Person
AAUOC o-- "0..*" Location

Conference"0..*"  --- "0..*" Person : attendsTo

BoardMeeting"0..*"  --- "0..*" BoardMember : attendsTo

@enduml