@startuml
Class AAUOC{
newLocation(I:Location) : void
newEvent(e:Event) : void
newPerson(p:Person) : void
informEvent(e:Event) : void
register(m:Member, e:Event) : void
}
Class Person{
name : String
}
Class Location{
description : String
address : String
}
Class Event{
date: Date
description : String
assign(l : Location) : void
}
Class Member{
e-mail : String
}
Class Conference{
max_attendees : Integer
}

Event <|-- Conference
Event <|-- BoardMeeting

Event -- Location : isLocatedIn
Event -- Member : attendsTo

Person <|-- Member
Member <|-- BoardMember

AAUOC o-- Event
AAUOC o-- Person
AAUOC o-- Location

Conference --- Person : attendsTo

BoardMeeting --- BoardMember : attendsTo

@enduml